import{a as L,i as y,S as w}from"./assets/vendor-u8rapaCG.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const b="46088453-a04f0c5be5b11b3b84520e583",E="https://pixabay.com/api/";async function S(t,n=1){try{return(await L.get(E,{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15}})).data}catch(r){throw new Error(`Error fetching images: ${r.response.status} ${r.response.statusText}`)}}function q(t){const n=document.querySelector(".gallery"),r=t.map(({webformatURL:a,largeImageURL:e,tags:o,likes:s,views:p,comments:g,downloads:h})=>`
            <li class="gallery-item">
                <a href="${e}" class="gallery-link">
                    <img src="${a}" alt="${o}" class="gallery-image" />
                </a>
                <div class="info">
                    <p class="info-item"><span>Likes</span> ${s}</p>
                    <p class="info-item"><span>Views</span> ${p}</p>
                    <p class="info-item"><span>Comments</span> ${g}</p>
                    <p class="info-item"><span>Downloads</span> ${h}</p>
                </div>
            </li>
        `).join("");n.insertAdjacentHTML("beforeend",r)}function $(){document.querySelector(".gallery").innerHTML=""}function c(t){y.error({title:"Error",message:t})}function v(){y.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})}function P(){document.querySelector(".loader").style.display="flex"}function M(){document.querySelector(".loader").style.display="none"}const B=document.querySelector(".search-form"),O=document.querySelector(".gallery"),d=document.querySelector(".load-more");let x=new w(".gallery a"),l=1,i="",f=0;B.addEventListener("submit",A);d.addEventListener("click",H);async function A(t){if(t.preventDefault(),i=t.target.elements.query.value.trim(),!i){c("Please enter a search query.");return}l=1,$(),u(),await m(i,l)}async function H(){l+=1,await m(i,l)}async function m(t,n){P();try{const r=await S(t,n);if(r.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!"),u();return}f=r.totalHits,q(r.hits),x.refresh(),O.children.length>=f?(u(),v()):I(),R()}catch(r){c(`Error fetching images: ${r.message}`)}finally{M()}}function I(){d.style.display="block"}function u(){d.style.display="none"}function R(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
