import{a as q,S as M,i as a}from"./assets/vendor-mdVVRe9K.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const P="46088453-a04f0c5be5b11b3b84520e583",R="https://pixabay.com/api/";async function g(e,n=1,o=15){try{return(await q.get(R,{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:o}})).data}catch(i){throw console.error("Error fetching images:",i),i}}let h=null;function p(e,n){const o=e.map(({webformatURL:i,largeImageURL:t,tags:r,likes:s,views:v,comments:S,downloads:E})=>`
    <li class="gallery-item">
        <a href="${t}" >
        <img class="gallery-img" src="${i}" alt="${r}" loading="lazy" />
        <div class="info">
        <p><b>Likes</b> ${s}</p>
        <p><b>Views</b> ${v}</p>
        <p><b>Comments</b> ${S}</p>
        <p><b>Downloads</b> ${E}</p>
      </div>
      </a>
      </li>
  `).join("");n.insertAdjacentHTML("beforeend",o),h?h.refresh():h=new M(".gallery a")}function $(e){e.innerHTML=""}function y(e){e.classList.remove("hidden")}function b(e){e.classList.add("hidden")}function B(e){e.classList.remove("hidden")}function L(e){e.classList.add("hidden")}const w=document.querySelector("#search-form"),d=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector("#load-more");let c=1,m="",l=0;w.addEventListener("submit",O);f.addEventListener("click",H);async function O(e){e.preventDefault();const n=e.target.elements.searchQuery.value.trim();if(n===""){a.warning({message:"Please enter a search query!",position:"topRight"});return}m=n,c=1,l=0,$(d),I(),L(f),y(u);try{const o=await g(m,c);if(l=o.totalHits,o.hits.length===0){a.error({message:"No images found. Try again!",position:"topRight"});return}p(o.hits,d),l>15&&B(f)}catch(o){a.error({message:"Something went wrong.",position:"topRight"}),console.error("Error fetching images:",o)}finally{b(u)}}async function H(){c+=1,y(u);try{const e=await g(m,c);p(e.hits,d),x(),c*15>=l&&(L(f),a.info({message:"You've reached the end of search results.",position:"topRight"}))}catch(e){a.error({message:"Something went wrong.",position:"topRight"}),console.error("Error fetching more images:",e)}finally{b(u)}}function I(){w.elements.searchQuery.value=""}function x(){const{height:e}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
